project_name: remarked
release:
  github:
    owner: zerok
    name: remarked
brew:
  install: bin.install "remarked"
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  main: ./cmd/remarked
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: remarked
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - LICENSE
  - README.md
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
